FC234 – Example Project
FC234 Program
266 statements
Source File
Uses
geometry
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
call homogeneous_constraints_overlap(n_constr)
! do the SVD of the overlap allocate(us(n_constr,ngr),vs(ngr,ngr),ws(ngr)) us = ahom call svdcmp(us,n_constr,ngr,n_constr,ngr,ws,vs)
give warnings if any column in aforce is totally zero
do the SVD decomposition
Add the correction term to the old solution
Calls
Contents
Variables
i j n3 rank iunit tra rot hua eliminate_fc fcalloc xt fn poscar outcar ex newamat newbmat afrc bfrc aux1 frc_constr auxi error ermax sd sig tim now today zone
Variables
Type Attributes Name Initial
integer :: i
integer :: j
integer :: n3
integer :: rank
integer :: iunit
integer :: tra
integer :: rot
integer :: hua
integer :: eliminate_fc
integer :: fcalloc
character :: xt*1
character :: fn*11
character :: poscar*7
character :: outcar*7
logical :: ex
real(kind=8), allocatable :: newamat(:,:)
real(kind=8), allocatable :: newbmat(:)
real(kind=8), allocatable :: afrc(:,:)
real(kind=8), allocatable :: bfrc(:)
real(kind=8), allocatable :: aux1(:,:)
integer, allocatable :: frc_constr(:)
integer, allocatable :: auxi(:,:)
real(kind=8) :: error
real(kind=8) :: ermax
real(kind=8) :: sd(4)
real(kind=8) :: sig
real :: tim
character :: now*10
character :: today*8
character :: zone*5
Call graph
fc234 calls write_lat_fc, set_force_displacement_matrix, set_rotational_inv_constraints, warn, set_maxterms, svd_set, write_neighbors, make_r0g, write_correspondance2, set_huang_inv_constraints, identify_atoms_in_supercell, make_reciprocal_lattice, 2, check_zero_column, set_translational_inv_constraints, read_crystal, include_constraints, write_output_fc2, setup_maps, force_constants_init, calculate_and_write_displacements, 999, read_force_position_data, set_neighbor_list, 3, write_independent_fcs, 9, read_input, 4, remove_zeros, write_out
write_lat_fc calls 3, 9, 4, 1, length, findatom_sc
set_force_displacement_matrix calls 3, 4, 66, findatom_sc
set_rotational_inv_constraints calls 4, compare2previous_lines, 66
svd_set calls 3, svbksb, 99, svdcmp
write_neighbors calls 3
write_correspondance2 calls 2, 4, dfloat, length, findatom_sc
set_huang_inv_constraints calls 9, 8
identify_atoms_in_supercell calls 3, check_input_poscar_consistency_new
check_zero_column calls warn, find_t
set_translational_inv_constraints calls write_out, compare2previous_lines, length
read_crystal calls make_reciprocal_lattice, 9, write_out, calculate_volume, length
write_output_fc2 calls 2, 3, 4, length
setup_maps calls 9, write_out, get_dim, ustring, collect_force_constants, read_fcs_2
force_constants_init calls findatom, dlatmat2, unitcell, dsind, xmatinv, bomb, xvmlt, xvsub, xmatmlt, dcosd, datan
calculate_and_write_displacements calls 2, 3, direct_to_cart_aa, cart_to_direct_aa
read_force_position_data calls write_out, findword, allocate_pos
set_neighbor_list calls 2, 3, calculate_distance, sort
write_independent_fcs calls 3, 9
read_input calls allocate_primcell, allocate_mass
remove_zeros calls 4
write_out calls write_outrm, write_outrv, write_outiv, write_outv, write_outr, write_outi, write_outim
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
dlatmat2 calls bomb, xvsub
compare2previous_lines calls 99
write_outv calls 3
unitcell calls xmatmlt
write_outr calls 99
write_outi calls 99
collect_force_constants calls findatom, 99, force_constants, unique_force_constant
length calls lengthv, lengtha
xmatinv calls lubksb, ludcmp
findatom_sc calls dfloat
check_input_poscar_consistency_new calls 2, 3, 9, write_out, check
write_outim calls 99
direct_to_cart_aa calls direct_to_cart_v
cart_to_direct_aa calls cart_to_direct_v
force_constants calls findatom, xvmlt, unique_force_constant, xrowop2, permutations, findatom2
unique_force_constant calls findatom
permutations calls bomb