bomb – Example Project
bomb Subroutine
6 statements
Source File
subroutine bomb()
Arguments
None
Called by
Contents
None
Call graph
force_constants_init calls bomb, dlatmat2
ifactorial calls bomb
permutations calls bomb
dlatmat2 calls bomb
fc234 calls force_constants_init, setup_maps
force_constants calls permutations
collect_force_constants calls force_constants
setup_maps calls collect_force_constants