calculate_and_write_displacements – Example Project
calculate_and_write_displacements Subroutine
31 statements
Source File
subroutine calculate_and_write_displacements()
Uses
geometry
lattice
ios
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
calculate_and_write_displacements calls 3, direct_to_cart_aa, 2, cart_to_direct_aa
direct_to_cart_aa calls direct_to_cart_v
cart_to_direct_aa calls cart_to_direct_v
fc234 calls calculate_and_write_displacements