cart_to_direct_v – Example Project
cart_to_direct_v Subroutine
9 statements
Source File
subroutine cart_to_direct_v(v, w)
Uses
geometry
lattice
Arguments
Type Intent Optional Attributes Name
type(vector) :: v
type(vector) :: w
Called by
Contents
None
Call graph
cart_to_direct_av calls cart_to_direct_v
cart_to_direct_aa calls cart_to_direct_v
calculate_and_write_displacements calls cart_to_direct_aa
pos_out_consistency calls cart_to_direct_aa
fc234 calls calculate_and_write_displacements