check_input_poscar_consistency_new – Example Project
check_input_poscar_consistency_new Subroutine
142 statements
Source File
subroutine check_input_poscar_consistency_new()
Uses
geometry
lattice
ios
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
check_input_poscar_consistency_new calls 9, 2, 3, check, write_out
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99
identify_atoms_in_supercell calls check_input_poscar_consistency_new
fc234 calls identify_atoms_in_supercell