check_input_poscar_consistency – Example Project
check_input_poscar_consistency Subroutine
95 statements
Source File
subroutine check_input_poscar_consistency()
Uses
geometry
lattice
ios
params
atoms_force_constants
Arguments
None
Calls
Contents
None
Call graph
check_input_poscar_consistency calls 3, 9, check, write_out
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99