check – Example Project
check Subroutine
18 statements
Source File
subroutine check(r, a1, a2, a3, ier, g1, g2, g3)
Uses
geometry
ios
params
Arguments
Type Intent Optional Attributes Name
type(vector) :: r
real(kind=8) :: a1
real(kind=8) :: a2
real(kind=8) :: a3
integer :: ier
type(vector) :: g1
type(vector) :: g2
type(vector) :: g3
Called by
Contents
None
Call graph
check_input_poscar_consistency_new calls check
check_input_poscar_consistency calls check
identify_atoms_in_supercell calls check_input_poscar_consistency_new
fc234 calls identify_atoms_in_supercell