collect_force_constants – Example Project
collect_force_constants Subroutine
143 statements
Source File
subroutine collect_force_constants(nrank, nshell, ngroups, ntermsindep, iatomtermindep, ixyztermindep, nterm6, iatomterm, ixyzterm, amat, ntermszero, iatomtermzero, ixyztermzero, maxrank, maxterms, maxtermsindep, maxtermszero, maxgroups, ierz, iert, ieri, ierg)
Uses
force_constants_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nrank
integer, intent(in) :: nshell(natoms0)
integer, intent(out) :: ngroups
integer, intent(out) :: ntermsindep(maxgroups)
integer, intent(out) :: iatomtermindep(maxrank,maxterms,maxgroups)
integer, intent(out) :: ixyztermindep(maxrank,maxterms,maxgroups)
integer, intent(out) :: nterm6(maxgroups)
integer, intent(out) :: iatomterm(maxrank,maxterms,maxgroups)
integer, intent(out) :: ixyzterm(maxrank,maxterms,maxgroups)
real(kind=8), intent(out) :: amat(maxterms,maxtermsindep,maxgroups)
integer, intent(out) :: ntermszero
integer, intent(out) :: iatomtermzero(maxrank,maxtermszero)
integer, intent(out) :: ixyztermzero(maxrank,maxtermszero)
integer, intent(in) :: maxrank
integer, intent(in) :: maxterms
integer, intent(in) :: maxtermsindep
integer, intent(in) :: maxtermszero
integer, intent(in) :: maxgroups
integer, intent(out) :: ierz
integer, intent(out) :: iert
integer, intent(out) :: ieri
integer, intent(out) :: ierg
Calls
Called by
Contents
None
Call graph
collect_force_constants calls findatom, 99, unique_force_constant, force_constants
unique_force_constant calls findatom
force_constants calls findatom, unique_force_constant, xvmlt, xrowop2, permutations, findatom2
permutations calls bomb
setup_maps calls collect_force_constants
fc234 calls setup_maps