compare2previous_lines – Example Project
compare2previous_lines Subroutine
40 statements
Source File
subroutine compare2previous_lines(m, n, a1d, a, counter, new)
Uses
geometry
ios
params
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=8), dimension(n) :: a1d
real(kind=8), dimension(m,n) :: a
integer :: counter
logical :: new
Calls
Called by
Contents
None
Call graph
compare2previous_lines calls 99
set_rotational_inv_constraints calls compare2previous_lines
set_translational_inv_constraints calls compare2previous_lines
fc234 calls set_rotational_inv_constraints, set_translational_inv_constraints