eliminate_fcs – Example Project
eliminate_fcs Subroutine
60 statements
Source File
subroutine eliminate_fcs(sig)
Uses
svd_stuff
ios
params
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: sig
Calls
Contents
None
Call graph
eliminate_fcs calls invsort, svd_set, inverse_real, write_output_fc2, write_independent_fcs
svd_set calls 3, svbksb, svdcmp, 99
write_output_fc2 calls length, 3, 2, 4
write_independent_fcs calls 9, 3
length calls lengthv, lengtha