findatom_sc – Example Project
findatom_sc Subroutine
23 statements
Source File
subroutine findatom_sc(n3, tau, iatom)
Uses
geometry
ios
lattice
atoms_force_constants
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n3(3)
integer, intent(in) :: tau
integer, intent(out) :: iatom
Calls
Called by
Contents
None
Call graph
findatom_sc calls dfloat
write_lat_fc calls findatom_sc
write_correspondance2 calls findatom_sc
write_correspondance calls findatom_sc
set_force_displacement_matrix calls findatom_sc
fc234 calls write_lat_fc, write_correspondance2, set_force_displacement_matrix
write_output_fc calls write_lat_fc