findatom – Example Project
findatom Subroutine
18 statements
Source File
subroutine findatom(icell, icell0, iatom)
Uses
force_constants_module
find atom in data base
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: icell(3)
integer, intent(in) :: icell0
integer, intent(out) :: iatom
Called by
Contents
None
Call graph
force_constants_init calls findatom
collect_force_constants calls findatom, unique_force_constant, force_constants
unique_force_constant calls findatom
force_constants calls findatom, unique_force_constant
fc234 calls force_constants_init, setup_maps
setup_maps calls collect_force_constants