force_constants – Example Project
force_constants Subroutine
303 statements
Source File
subroutine force_constants(nrank, iatomd, ixyzd, ntermsindep, iatomtermindep, ixyztermindep, nterm5, iatomtermall, ixyztermall, amat, ntermszero, iatomtermzero, ixyztermzero, maxrank, maxterms, maxtermsindep, maxtermszero, ierz, iert, ieri)
Uses
force_constants_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nrank
integer, intent(in) :: iatomd(nrank)
integer, intent(in) :: ixyzd(nrank)
integer, intent(out) :: ntermsindep
integer, intent(out) :: iatomtermindep(maxrank,maxterms)
integer, intent(out) :: ixyztermindep(maxrank,maxterms)
integer, intent(out) :: nterm5
integer, intent(out) :: iatomtermall(maxrank,maxterms)
integer, intent(out) :: ixyztermall(maxrank,maxterms)
real(kind=8), intent(out) :: amat(maxterms,maxtermsindep)
integer, intent(out) :: ntermszero
integer, intent(out) :: iatomtermzero(maxrank,maxtermszero)
integer, intent(out) :: ixyztermzero(maxrank,maxtermszero)
integer, intent(in) :: maxrank
integer, intent(in) :: maxterms
integer, intent(in) :: maxtermsindep
integer, intent(in) :: maxtermszero
integer, intent(out) :: ierz
integer, intent(out) :: iert
integer, intent(out) :: ieri
Calls
Called by
Contents
None
Call graph
force_constants calls xrowop2, findatom, xvmlt, unique_force_constant, permutations, findatom2
unique_force_constant calls findatom
permutations calls bomb
collect_force_constants calls force_constants
setup_maps calls collect_force_constants
fc234 calls setup_maps