force_constants_init – Example Project
force_constants_init Subroutine
253 statements
Source File
subroutine force_constants_init(lattparams, primlatt, natoms_in, iatomtype, atompos_in)
Uses
force_constants_module
lattice
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: lattparams(6)
real(kind=8), intent(in) :: primlatt(3,3)
integer, intent(in) :: natoms_in
integer, intent(in) :: iatomtype(natoms_in)
real(kind=8), intent(in) :: atompos_in(3,natoms_in)
Calls
Called by
Contents
None
Call graph
force_constants_init calls xmatinv, dcosd, findatom, datan, xvmlt, bomb, xvsub, dlatmat2, dsind, xmatmlt, unitcell
xmatinv calls lubksb, ludcmp
dlatmat2 calls bomb, xvsub
unitcell calls xmatmlt
fc234 calls force_constants_init