identify_atoms_in_supercell – Example Project
identify_atoms_in_supercell Subroutine
27 statements
Source File
subroutine identify_atoms_in_supercell()
Uses
geometry
lattice
ios
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
identify_atoms_in_supercell calls check_input_poscar_consistency_new, 3
check_input_poscar_consistency_new calls 3, 9, 2, check, write_out
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99
fc234 calls identify_atoms_in_supercell