make_reciprocal_lattice_2pi – Example Project
make_reciprocal_lattice_2pi Subroutine
17 statements
Source File
subroutine make_reciprocal_lattice_2pi(r1, r2, r3, g1, g2, g3)
Uses
geometry
ios
constants
Arguments
Type Intent Optional Attributes Name
type(vector) :: r1
type(vector) :: r2
type(vector) :: r3
type(vector) :: g1
type(vector) :: g2
type(vector) :: g3
Calls
Contents
None
Call graph
make_reciprocal_lattice_2pi calls write_out
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99