make_sorted_gs – Example Project
make_sorted_gs Subroutine
29 statements
Source File
subroutine make_sorted_gs(g1, g2, g3, nshell, gg)
Uses
geometry
Arguments
Type Intent Optional Attributes Name
type(vector) :: g1
type(vector) :: g2
type(vector) :: g3
integer :: nshell
real(kind=8) :: gg(3,nshell)
Calls
Contents
None
Call graph
make_sorted_gs calls sort, length, 9
length calls lengthv, lengtha