pos_out_consistency – Example Project
pos_out_consistency Subroutine
27 statements
Source File
subroutine pos_out_consistency()
Uses
geometry
lattice
ios
params
atoms_force_constants
Arguments
None
Calls
Contents
None
Call graph
pos_out_consistency calls direct_to_cart_aa, cart_to_direct_aa
direct_to_cart_aa calls direct_to_cart_v
cart_to_direct_aa calls cart_to_direct_v