read_crystal – Example Project
read_crystal Subroutine
99 statements
Source File
subroutine read_crystal(poscar)
Uses
geometry
lattice
ios
params
atoms_force_constants
Arguments
Type Intent Optional Attributes Name
character :: poscar*(*)
Calls
Called by
Contents
None
Call graph
read_crystal calls 9, length, make_reciprocal_lattice, calculate_volume, write_out
length calls lengthv, lengtha
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99
fc234 calls read_crystal