read_force_position_data – Example Project
read_force_position_data Subroutine
70 statements
Source File
subroutine read_force_position_data(outcar, frc_constr)
Uses
geometry
lattice
svd_stuff
ios
params
atoms_force_constants
Arguments
Type Intent Optional Attributes Name
character :: outcar*(*)
integer :: frc_constr
Calls
Called by
Contents
None
Call graph
read_force_position_data calls findword, allocate_pos, write_out
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99
fc234 calls read_force_position_data