read_input – Example Project
read_input Subroutine
68 statements
Source File
subroutine read_input()
Uses
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
read_input calls allocate_primcell, allocate_mass
fc234 calls read_input