set_neighbor_list – Example Project
set_neighbor_list Subroutine
61 statements
Source File
public subroutine set_neighbor_list()
Uses
geometry
lattice
ios
force_constants_module
params
Arguments
None
Calls
Called by
Contents
None
Call graph
set_neighbor_list calls sort, 2, calculate_distance, 3
fc234 calls set_neighbor_list