set_force_displacement_matrix – Example Project
set_force_displacement_matrix Subroutine
202 statements
Source File
subroutine set_force_displacement_matrix(frc_constr, afrc, bfrc)
Uses
geometry
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
Type Intent Optional Attributes Name
integer :: frc_constr
real(kind=8) :: afrc(frc_constr,ngr)
real(kind=8) :: bfrc(frc_constr)
Calls
Called by
Contents
None
Call graph
set_force_displacement_matrix calls findatom_sc, 66, 4, 3
findatom_sc calls dfloat
fc234 calls set_force_displacement_matrix