set_rotational_inv_constraints – Example Project
set_rotational_inv_constraints Subroutine
368 statements
Source File
subroutine set_rotational_inv_constraints()
Uses
geometry
svd_stuff
ios
force_constants_module
params
atoms_force_constants
sets the rotational invariance part of the amatrx
Arguments
None
Calls
Called by
Contents
None
Call graph
set_rotational_inv_constraints calls 66, 4, compare2previous_lines
compare2previous_lines calls 99
fc234 calls set_rotational_inv_constraints