set_translational_inv_constraints – Example Project
set_translational_inv_constraints Subroutine
190 statements
Source File
subroutine set_translational_inv_constraints()
Uses
geometry
svd_stuff
ios
force_constants_module
params
atoms_force_constants
sets the translational invariance part of the amatrx
Arguments
None
Calls
Called by
Contents
None
Call graph
set_translational_inv_constraints calls length, compare2previous_lines, write_out
length calls lengthv, lengtha
compare2previous_lines calls 99
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99
fc234 calls set_translational_inv_constraints