set_neighbork – Example Project
set_neighbork Subroutine
39 statements
Source File
subroutine set_neighbork(nkp, kp, nb, nbk, nbmax, kcutoff, nshl, gg)
Uses
geometry
ios
lattice
Arguments
Type Intent Optional Attributes Name
integer :: nkp
real(kind=8) :: kp(3,nkp)
integer :: nb(nkp,nbmax)
integer :: nbk(nkp)
integer :: nbmax
real(kind=8) :: kcutoff
integer :: nshl
real(kind=8) :: gg(3,nshl)
Calls
Contents
None
Call graph
set_neighbork calls 3, length, 7
length calls lengthv, lengtha