set_huang_inv_constraints – Example Project
set_huang_inv_constraints Subroutine
75 statements
Source File
subroutine set_huang_inv_constraints()
Uses
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
set_huang_inv_constraints calls 9, 8
fc234 calls set_huang_inv_constraints