setup_maps – Example Project
setup_maps Subroutine
172 statements
Source File
subroutine setup_maps()
Uses
geometry
svd_stuff
ios
params
atoms_force_constants
maps the output of collect_fcs to the new arrays for each rank, with the proper (allocatable) dimensions
Arguments
None
Calls
Called by
Contents
None
Call graph
setup_maps calls 9, ustring, get_dim, read_fcs_2, collect_force_constants, write_out
collect_force_constants calls force_constants, findatom, unique_force_constant, 99
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
force_constants calls findatom, unique_force_constant, xrowop2, xvmlt, permutations, findatom2
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
unique_force_constant calls findatom
write_outv calls 3
write_outr calls 99
permutations calls bomb
fc234 calls setup_maps