svd_set – Example Project
svd_set Subroutine
93 statements
Source File
subroutine svd_set(m3, n, a, b, x, sig, svdcut, error, ermax, sigma, fnsvd)
Arguments
Type Intent Optional Attributes Name
integer :: m3
integer :: n
real(kind=8), intent(in) :: a(m3,n)
real(kind=8), intent(in) :: b(m3)
real(kind=8), intent(out) :: x(n)
real(kind=8), intent(out) :: sig(n)
real(kind=8) :: svdcut
real(kind=8), intent(out) :: error
real(kind=8), intent(out) :: ermax
real(kind=8) :: sigma
character :: fnsvd
Calls
Called by
Contents
None
Call graph
svd_set calls svdcmp, svbksb, 99, 3
eliminate_fcs calls svd_set
fc234 calls svd_set