write_output_fc2 – Example Project
write_output_fc2 Subroutine
105 statements
Source File
subroutine write_output_fc2()
Uses
constants
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
write_output_fc2 calls 3, 2, 4, length
length calls lengthv, lengtha
eliminate_fcs calls write_output_fc2
fc234 calls write_output_fc2