write_correspondance2 – Example Project
write_correspondance2 Subroutine
52 statements
Source File
subroutine write_correspondance2()
Uses
geometry
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
None
Calls
Called by
Contents
None
Call graph
write_correspondance2 calls findatom_sc, length, 2, 4, dfloat
findatom_sc calls dfloat
length calls lengthv, lengtha
fc234 calls write_correspondance2