write_independent_fcs – Example Project
write_independent_fcs Subroutine
44 statements
Source File
subroutine write_independent_fcs(sd)
Uses
svd_stuff
ios
params
atoms_force_constants
fc1 = fc1-matmul(a11ia12,fcs)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(out) :: sd(4)
Calls
Called by
Contents
None
Call graph
write_independent_fcs calls 3, 9
eliminate_fcs calls write_independent_fcs
fc234 calls write_independent_fcs