write_outiv – Example Project
write_outiv Subroutine
9 statements
Source File
public subroutine write_outiv(unit, string, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
integer, dimension(:) :: var
Calls
Called by
Contents
None
Call graph
write_outiv calls 99
write_out calls write_outiv
check_input_poscar_consistency_new calls write_out
read_force_position_data calls write_out
check_input_poscar_consistency calls write_out
set_translational_inv_constraints calls write_out
read_crystal calls write_out
fc234 calls write_out, read_force_position_data, set_translational_inv_constraints, read_crystal, setup_maps, identify_atoms_in_supercell
make_reciprocal_lattice_2pi calls write_out
setup_maps calls write_out
identify_atoms_in_supercell calls check_input_poscar_consistency_new