write_lat_fc – Example Project
write_lat_fc Subroutine
53 statements
Source File
subroutine write_lat_fc(ngrps, ntrms)
Uses
constants
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
Type Intent Optional Attributes Name
integer :: ngrps(4)
integer :: ntrms(4)
Calls
Called by
Contents
None
Call graph
write_lat_fc calls findatom_sc, 9, length, 3, 4, 1
findatom_sc calls dfloat
length calls lengthv, lengtha
fc234 calls write_lat_fc
write_output_fc calls write_lat_fc