write_output_fc – Example Project
write_output_fc Subroutine
125 statements
Source File
subroutine write_output_fc()
Uses
constants
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
None
Calls
Contents
None
Call graph
write_output_fc calls 9, write_lat_fc, length, 2, 3, 4, 1
write_lat_fc calls 9, length, 3, 4, 1, findatom_sc
length calls lengthv, lengtha
findatom_sc calls dfloat