write_correspondance – Example Project
write_correspondance Subroutine
50 statements
Source File
subroutine write_correspondance()
Uses
geometry
lattice
svd_stuff
ios
force_constants_module
params
atoms_force_constants
Arguments
None
Calls
Contents
None
Call graph
write_correspondance calls findatom_sc, length, 2, 4, dfloat
findatom_sc calls dfloat
length calls lengthv, lengtha