xvmlt – Example Project
xvmlt Subroutine
15 statements
Source File
subroutine xvmlt(x, v1, v2, nrow, ncol, nr)
multiply a double precision vector by a double precision matrix, v2=x*v1
Arguments
Type Intent Optional Attributes Name
double precision :: x(nr,ncol)
double precision :: v1(ncol)
double precision :: v2(nrow)
integer :: nrow
integer :: ncol
integer :: nr
Called by
Contents
None
Call graph
force_constants_init calls xvmlt
force_constants calls xvmlt
getstar calls xvmlt
fc234 calls force_constants_init, setup_maps
collect_force_constants calls force_constants
setup_maps calls collect_force_constants