xvsub – Example Project
xvsub Subroutine
8 statements
Source File
subroutine xvsub(v1, v2, v3, nrow)
subtract two real vectors: v3=v1-v2
Arguments
Type Intent Optional Attributes Name
double precision :: v1(nrow)
double precision :: v2(nrow)
double precision :: v3(nrow)
integer :: nrow
Called by
Contents
None
Call graph
force_constants_init calls xvsub, dlatmat2
dlatmat2 calls xvsub
getstar calls xvsub
fc234 calls force_constants_init