assignment(=) – Example Project
assignment(=) Interface
3 statements
Source File
public interface assignment(=)
Calls
Contents
Module Procedures
array_eq_vector array_eq_point vector_eq_array vector_eq_point point_eq_vector point_eq_array
Module Procedures
public subroutine array_eq_vector(a, v)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(out) :: a(3)
type(vector), intent(in) :: v
public subroutine array_eq_point(a, p)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(out) :: a(3)
type(point), intent(in) :: p
public subroutine vector_eq_array(vv, aa)
Arguments
Type Intent Optional Attributes Name
type(vector), intent(out) :: vv
real(kind=8), intent(in) :: aa(3)
public subroutine vector_eq_point(v, p)
Arguments
Type Intent Optional Attributes Name
type(vector), intent(out) :: v
type(point), intent(in) :: p
public subroutine point_eq_vector(p, v)
Arguments
Type Intent Optional Attributes Name
type(point), intent(out) :: p
type(vector), intent(in) :: v
public subroutine point_eq_array(p, a)
Arguments
Type Intent Optional Attributes Name
type(point), intent(out) :: p
real(kind=8), intent(in) :: a(3)
Call graph
assignment(=) calls point_eq_vector, point_eq_array, vector_eq_point, vector_eq_array, array_eq_vector, array_eq_point