length – Example Project
length Interface
3 statements
Source File
public interface length
Calls
Called by
Contents
Module Procedures
lengthv lengtha
Module Procedures
public function lengthv(v) result(l)
Arguments
Type Intent Optional Attributes Name
type(vector), intent(in) :: v
Return Value real(kind=8)
public function lengtha(v) result(l)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:) :: v
Return Value real(kind=8)
Call graph
length calls lengthv, lengtha
write_lat_fc calls length
set_neighbork calls length
write_correspondance calls length
set_translational_inv_constraints calls length
read_crystal calls length
write_output_fc2 calls length
read_output_fc2 calls length
write_output_fc calls length, write_lat_fc
write_correspondance2 calls length
make_sorted_gs calls length
fc234 calls write_lat_fc, set_translational_inv_constraints, read_crystal, write_output_fc2, write_correspondance2
eliminate_fcs calls write_output_fc2