operator(.myeq.) – Example Project
operator(.myeq.) Interface
3 statements
Source File
public interface operator(.myeq.)
Calls
Contents
Module Procedures
myequal myequalarray myequalvector
Module Procedures
public function myequal(v, w) result(eq)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: v
real(kind=8), intent(in) :: w
Return Value logical
public function myequalarray(v, w) result(eq)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:) :: v
real(kind=8), intent(in), dimension(:) :: w
Return Value logical
public function myequalvector(v, w) result(eq)
Arguments
Type Intent Optional Attributes Name
type(vector), intent(in) :: v
type(vector), intent(in) :: w
Return Value logical
Call graph
operator(.myeq.) calls myequalvector, myequalarray, myequal
myequalarray calls myequal