write_out – Example Project
write_out Interface
3 statements
Source File
public interface write_out
Calls
Called by
Contents
Module Procedures
write_outiv write_outrv write_outim write_outrm write_outi write_outr write_outv
Module Procedures
public subroutine write_outiv(unit, string, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
integer, dimension(:) :: var
public subroutine write_outrv(unit, string, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
real(kind=8), dimension(:) :: var
public subroutine write_outim(unit, string, n, m, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
integer :: n
integer :: m
integer :: var(n,m)
public subroutine write_outrm(unit, string, n, m, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
integer :: n
integer :: m
real(kind=8) :: var(n,m)
public subroutine write_outi(unit, string, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
integer :: var
public subroutine write_outr(unit, string, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
real(kind=8) :: var
public subroutine write_outv(unit, string, var)
Arguments
Type Intent Optional Attributes Name
integer :: unit
character(len=*) :: string
type(vector) :: var
Call graph
write_out calls write_outim, write_outrm, write_outrv, write_outiv, write_outi, write_outv, write_outr
write_outim calls 99
write_outrm calls 99
write_outrv calls 99
write_outiv calls 99
write_outi calls 99
write_outv calls 3
write_outr calls 99
check_input_poscar_consistency_new calls write_out
read_force_position_data calls write_out
check_input_poscar_consistency calls write_out
set_translational_inv_constraints calls write_out
read_crystal calls write_out
fc234 calls write_out, read_force_position_data, set_translational_inv_constraints, read_crystal, setup_maps, identify_atoms_in_supercell
make_reciprocal_lattice_2pi calls write_out
setup_maps calls write_out
identify_atoms_in_supercell calls check_input_poscar_consistency_new