# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py  # Adjusted to match your folder structure

python:
  install:
    - requirements: docs/requirements.txt  # Path to your requirements.txt file
